### PR TITLE
Update tarball sha and feedstock for conda-smithy

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by ericdill** [comment]
@parente this build had some oddities on travis. restarted the job

**Comment by parente** [comment]
Started again. Looks like both appveyor and travis had issues downloading miniconda.

**Comment by parente** [comment]
Same issue on travis again. Trying the curl command from here, it gets a 301 Moved Permanently with a new location of https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh. So, it's now https. 

Looks like the template in conda-smithy already switched to https. Maybe the one here is due for another re-render.

**Comment by ericdill** [comment]
@jakirkham @filipe I assume that this is a known issue?

**Comment by ericdill** [comment]
Err @ocefpaf 😑

**Comment by jakirkham** [comment]
Please upgrade `conda-smithy` and re-render again. Note re-render takes a `-c`/`--commit` argument to commit changes.

**Comment by parente** [comment]
Should be good to go now. I'll rebase the 0.3.1 PR on master after merge.

**Comment by ericdill** [comment]
lgtm! Thanks @parente

**Comment by jakirkham** [comment]
Oh I forgot to tell you guys the response from GitHub (or perhaps I forgot that I told you 😄).

In any event, they said that they do run checks to avoid this sort of issue (checksums changing on a tarball), but sometimes they miss something. In any event, they don't guarantee that the checksum won't ever change.

The reason it can change is content like the tarball and zip provided for each tag are generated on demand. Likely they run `git archive` and maybe some other stuff. So they are not cached anywhere. As a result, if the process for generating these changes the final result, the checksum itself can change.

So just be aware this can happen. Maybe try running `git archive` yourself and comparing to their tarballs when this happens to make sure everything is ok.

**Pull request merged**
