### PR TITLE
Package for 0.3.0 release

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by ericdill** [comment]
Lgtm

**Comment by jakirkham** [comment]
Please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.2`.

**Comment by parente** [comment]
Re-smithy-ed.

**Comment by jakirkham** [comment]
Thanks.

Also FYI one of the Travis jobs stalled out. So have restarted it.

**Comment by ericdill** [comment]
How do you know when to rerender the feedstock?

**Pull request merged**
