### PR TITLE
Fix the recipe summary

### PR DESCRIPTION
**Pull request by parente**
Looks like a copy/paste from another recipe

### CODE REVIEW

**Review by ericdill — APPROVED** [review]
Haha good catch

**Comment by ericdill** [comment]
Bleh can't merge from phone because ci haven't finished yet

**Comment by mariusvniekerk** [comment]
Probably need to bump build number?

**Review by mariusvniekerk — APPROVED** [review]

**Comment by jakirkham** [comment]
Please close and fork. Then please reissue the PR from a branch on your fork.

**Comment by parente** [comment]
That's what I get for doing a quick text  fix in the github UI.

**Comment by jakirkham** [comment]
Yeah, the GitHub UI can be a bit annoying. Though if you want to go that route, first go to your fork and then make the changes in the web editor. Once done it will try to create a PR to your fork. So you need to chose the original feedstock and apply the PR there.

**Pull request closed without merging**
